language: node_js
cache: npm
node_js:
  - "node"

install:
  - npm ci

script:
  - npm run build
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ];
    then node ./dist/js/scraper.js;
    else curl --fail https://jkuroomsearch.app/data/rooms.json -o rooms.json;
    fi

after_success:
  - mkdir ./dist/data
  - mv rooms.json ./dist/data

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: main