language: node_js
cache: npm
node_js:
  - "node"

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master